#!/bin/sh
year=1953
year2=1974
while [ $year -le $year2 ] ; do
echo $year
cat ${year}01/flx.${year}01.avrg.grib ${year}02/flx.${year}02.avrg.grib ${year}03/flx.${year}03.avrg.grib ${year}04/flx.${year}04.avrg.grib  ${year}05/flx.${year}05.avrg.grib  ${year}06/flx.${year}06.avrg.grib  ${year}07/flx.${year}07.avrg.grib  ${year}08/flx.${year}08.avrg.grib  ${year}09/flx.${year}09.avrg.grib  ${year}10/flx.${year}10.avrg.grib  ${year}11/flx.${year}11.avrg.grib  ${year}12/flx.${year}12.avrg.grib >  flx.${year}.grib

year=`expr $year \+ 1`
done


